# Generated by Django 4.1.7 on 2023-03-07 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fishing_holes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fish_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishpost',
            name='fishing_hole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing_holes.fishinghole'),
        ),
        migrations.AddField(
            model_name='fishpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
