# Generated by Django 4.1.7 on 2023-03-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishpost',
            name='photo',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
