# Generated by Django 4.1.7 on 2023-03-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_posts', '0003_alter_fishpost_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishpost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
