# Generated by Django 4.1.7 on 2023-03-07 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fish_posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishingHole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=225)),
                ('latitude', models.FloatField(max_length=225)),
                ('longitude', models.FloatField(max_length=225)),
                ('parking', models.CharField(max_length=225)),
                ('restroom', models.CharField(max_length=225)),
                ('record_fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish_posts.fishpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
