# Generated by Django 4.1.7 on 2023-03-08 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish_posts', '0002_initial'),
        ('fishing_holes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishinghole',
            name='record_fish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fish_posts.fishpost'),
        ),
    ]
