# Generated by Django 4.1.7 on 2023-04-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_holes', '0003_remove_fishinghole_restroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishinghole',
            name='restroom',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
